### ISSUE TITLE
Create Midline survey form

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/uninhibited#12]
## Context: 
we need to create a form to allow users to fill the midline form which is a part of this study. 
- this form is to be filled out for those students who have attended the weekly session. 
- it is "**Not**" mandatory to fill this form for those with a baseline as well, so the team can randomly pick any student of the school who has attended the weekly session. as the sample for baseline, midline or end-line will be 20-30% of total students only.

Please refer process flow to understand the steps and logic better: https://docs.google.com/spreadsheets/d/1FbHVIISvMqfunwiDBZfwmXeJkIqAnpOwrMWYcZsWcZw/edit#gid=1165697959

Midline form requirement link: https://docs.google.com/spreadsheets/d/1FbHVIISvMqfunwiDBZfwmXeJkIqAnpOwrMWYcZsWcZw/edit#gid=885167309

**Comment by Dinesh2019** [comment]
- [x] "For users who mentioned using cloth/stitched cloth pads-
Whenever you last used cloth, where did you dry it?" according to the requirement the question should display only if the person selected cloth in Q7 but it shows without selecting any option **Fixed**
- [x]  What did you use to wash your private area during your last menstrual period? As per the requirement it is single select but we have developed as multi-select -**Fixed**
- [x]  What did you do after speaking on the helpline? - as per the requirement should display only if the question What was the reason for calling? is answered otherwise we should skip this question **Fixed**
- [x]  What did you do after speaking on the helpline? should be multi select but it is single select **Fixed**
- [x]  During your last period, If you missed school on all or some days, what were the reasons? should display only Only if 'b' and 'c' are selected for the above question but is displayed of all the options  and alos we need to handle if the option is selected as other **Fixed**
- [ ]  Currently we are not doing weekly session or baseline we have just developed midline session and it is unplanned visit and we scheduled n number time - For now we are not fixing this 
- [x]  Mandatory is applied for all but as per the requirement only two question is manadtory
