### ISSUE TITLE
Pre-menarche baseline form creation

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/uninhibited#20]
## Context:
we have developed survey forms for students from 9-12 standard, here we are supposed to create baseline form for 6th - 8th Standard students. we are adding more form to include Pre-menarche in the scope now.

Please refer this requirement document to create it: https://docs.google.com/spreadsheets/d/1FbHVIISvMqfunwiDBZfwmXeJkIqAnpOwrMWYcZsWcZw/edit#gid=448813091

- [x] Add class 6th, 7th, & 8th in student registration form where class is mentioned: https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/uninhibited/11

- [x] Create baseline form for Students who's class is 6th, 7th or 8th.
- [x] based on class show forms, this form is to be show only to class 6th, 7th, & 8th standard.

Note: for 9th, 10th, 11th, and 12th Standard this form should be shown: https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/uninhibited/12

**Comment by adamsanadi6** [comment]
@salilsamanvay Moving this card to "On Hold". Discussed with @nupoorkhandelwal . The card mentions subject registration, but after discussing this with @nupoorkhandelwal , it was clarified that it pertains to the encounter, not subject registration. Since the requirements on this card are not articulated correctly, I am moving this card to "On Hold".

**Comment by salilsamanvay** [comment]
@adamsanadi6 I have added steps on the card, moving it to tech lead review lane. @nupoorkhandelwal see if you are ok with this card now.
